### ISSUE TITLE
Using this to learn!

### ISSUE THREAD

**Issue by HBGDEV** [99Anvar99/Aera#2]
I come from UC 

Using Your menu to learn everything again 

I had an ols menu that i used to use but Its all outdated so im here learning again 

one thing i have noticed is that the menu Once in a submenu dosnt allow for Going back to prevous section in the menu 

(hopefully that makes sense) 

i am assuming we have to loop the submenus so that there constantly open??? or create tabs

**Comment by 99Anvar99** [comment]
## Greetings @MONKE-MODZ.
Thank you for being interested in learning this base.

- 1) If i am understanding correctly the menu closes when you are trying to go back a submenu?

- 2) I believe that looping the submenu is kind of pointless, but its useful in some cases such as players and other places that might needed to be looped.

### Solution
- I will make sure that the bug with the menu closing will be fixed very soon, and about looping the submenu i could make it that you could select the submenu that you would like to loop.

**Comment by HBGDEV** [comment]
So Ive got it up and running 

figured out where all the submenus are and whatnot And im attempting to add some small features like Superjump (using natives and applying force to entity) 

Now with that being said (features are probably dtc XD) 

i cant figure out how I make it a toggle and not looped 

sorry for the Noob question! Im used to BBV2 / BBV1 

The features im using are from one of my old menus (to get the swing of things again) 

they use this: 
bool superjump 
void superjump()
{
insert shit here
}

**Comment by 99Anvar99** [comment]
> So Ive got it up and running
> 
> figured out where all the submenus are and whatnot And im attempting to add some small features like Superjump (using natives and applying force to entity)
> 
> Now with that being said (features are probably dtc XD)
> 
> i cant figure out how I make it a toggle and not looped
> 
> sorry for the Noob question! Im used to BBV2 / BBV1
> 
> The features im using are from one of my old menus (to get the swing of things again)
> 
> they use this: bool superjump void superjump() { insert shit here }

- I have already added a **(Task Jump Constructor)** for super jump/beast jump
and its already in the self tab

- Also if you want to loop things check out commands>features

And lastly
```
bool superjump
void superjump()
{
  insert shit here
}
``` 
is not a very good (more like very shitty) coding style. more like copy and pasted from leaked sources from 2019

Also none of the code is **DETECTED** if so provide proof

**Comment by HBGDEV** [comment]
I wasnt talking about your code! I was talking about mine XD 


i want to get back into making stuff i was wondering instead of filling up here i could private message you on DC?

*EDITD*

Its not that i want things to loop Its that i dont want them to loop

**Comment by 99Anvar99** [comment]
Oh my fault, i have read the message wrong

and yes you can message me on discord: mister_998

- EDIT:
in the future commits i will add: On enable, on tick, on disable
