### ISSUE TITLE
How do I add  font for it

### ISSUE THREAD

**Issue by WoShiMengHuA** [99Anvar99/Aera#5]
I want to use chinese to write some option name.
But the menu default font can't display chinse, the chinese word will be "???".
So,I need add others font to the menu for show chinese word.
Can you tell me how can I add the other font (like MicrosoftYaHei) to the menu?
Thank you

**Comment by 99Anvar99** [comment]
> I want to use chinese to write some option name. But the menu default font can't display chinse, the chinese word will be "???". So,I need add others font to the menu for show chinese word. Can you tell me how can I add the other font (like MicrosoftYaHei) to the menu? Thank you

Hi @WoShiMengHuA 
Yes, I will add an commented example for adding fonts that support different languages. Example will be located in Renderer.cpp

**Comment by 99Anvar99** [comment]
@WoShiMengHuA I have now added a example for **fonts to support different languages!**

**Comment by WoShiMengHuA** [comment]
Thank you🥰
