### ISSUE TITLE
Crashing on unload

### ISSUE THREAD

**Issue by ji8sw** [99Anvar99/Aera#8]
Aera crashes when unloading 100% of the time, with no modifications, is this a me thing?
[Log.txt](https://github.com/99Anvar99/Aera/files/15444228/Log.txt)

**Comment by 99Anvar99** [comment]
Interesting.  It works fine for me, I'm not quite sure why it would crash on unload.  I will have to take a look when I'm available 

Thank you for letting me know

**Comment by ji8sw** [comment]
Hmmm, I don't know. Seems to only be that project, I redownloaded the source and added all my changes (it was happening before the changes) and it works fine and unloads immediately.
