### ISSUE TITLE
offsets

### ISSUE THREAD

**Issue by Noritem** [99Anvar99/Aera#9]
Lol

**Comment by Bam810bam321** [comment]
> you bro you have the fivem offsets??

this is for GTA SP

**Comment by 99Anvar99** [comment]
> you bro you have the fivem offsets??

This is only for GTA5 and not RP/FiveM

**Comment by 99Anvar99** [comment]
> > you bro you have the fivem offsets??
> 
> this is for GTA SP

Yes and for online.

**Comment by Noritem** [comment]
yes i know is just wanted to ask but thanks
